### ISSUE TITLE
Editor Value Update

### ISSUE THREAD

**Issue by Sharan-Babu** [Ghasel/streamlit-ace#3]
Hi. With this component, I wish to make a voice-controlled code editor. So, each time a user presses a button, I want the value/code in the editor to be updated with the text in the user's voice.
But, I am not able to do this because of the way streamlit works. I face multiple 'key error' if I wrap the component with a function.
Else, the code in editor contains only the new text...

Can you please help me out with this?

**Comment by Ghasel** [comment]
Hello @Sharan-Babu,

Sorry for the late reply. Did you figure out how to solve your issue?

**Comment by Sharan-Babu** [comment]
I used a work around. Thanks.
